"""empty message

Revision ID: 671c8660824a
Revises: c11346d7033d
Create Date: 2023-09-16 09:40:57.863844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671c8660824a'
down_revision = 'c11346d7033d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='fk_location_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poly_region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Long', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='fk_region_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poly_region')
    op.drop_table('regions')
    # ### end Alembic commands ###
