"""empty message

Revision ID: c11346d7033d
Revises: 8f39a60aa08c
Create Date: 2023-09-16 08:57:45.292523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11346d7033d'
down_revision = '8f39a60aa08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phoneto_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=80), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], name='fk_protocol_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phoneto_call')
    # ### end Alembic commands ###
